---

- hosts: all
  tasks:
    - name: Install vim
      apt:
        name: vim
        state: present

- hosts: app
  tasks:
    - name: Install python setuptools
      apt:
        name: python-setuptools
        state: present
    - name: Install python pip
      apt:
        name: python-pip
        state: present
    - name: Install flask for python
      pip:
        name: flask
        state: present

- hosts: db
  tasks:
    - name: Install postgresql
      apt:
        name: postgresql
        state: present
    - name: Install postgresql-client
      apt:
        name: postgresql-client
        state: present
