- hosts: app
  tasks:
    - name: Install python setuptools
      apt:
        name: python-setuptools
        state: present
    - name: Install python pip
      apt:
        name: python-pip
        state: present
    - name: Install flask for python
      pip:
        name: flask
